name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Dotnet Build
        run: dotnet build --configuration Release

      - name: Generate EF migration script
        run: |
          dotnet tool install --global dotnet-ef
          dotnet ef migrations script --idempotent --no-build --configuration Release --project ./Web/Web.csproj --output ${{env.DOTNET_ROOT}}/migrations.sql --verbose

      - name: Dotnet Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/cotd-app

      - name: Upload EF migration script artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: dbmigrationscript
          path: ${{env.DOTNET_ROOT}}/migrations.sql

      - name: Upload application artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: cotdapp
          path: ${{env.DOTNET_ROOT}}/cotd-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download application artifact from build job
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: cotdapp

      - name: Download EF migration script artifact from build job
        id: download-migration-script
        uses: actions/download-artifact@v3
        with:
          name: dbmigrationscript
      
      - name: Migrate Database
        uses: azure/sql-action@v2.2
        with:
          connection-string: ${{ secrets.DB_CONNECTION_STRING }}
          path: ${{ steps.download-migration-script.outputs.download-path }}/migrations.sql
          action: "publish"
      
      - name: App settings variable substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: "${{ steps.download-artifact.outputs.download-path }}/appsettings.json"
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cotd-qualifier-rank-web'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1FB9D4E4837244188F886E967968C2C2 }}
          package: .
